zephyr: update include paths to use <zephyr/...>
zephyrproject-rtos/chre pull request #2
Opened 2022-05-10 13:41 UTC by gmarull

Zephyr has prefixed all of its includes with <zephyr/...>. While the old
mode can still be used (CONFIG_LEGACY_INCLUDE_PATH) and is still enabled
by default, it's better to be prepared for its removal in the future.

2022-05-13 15:57 UTC, MaureenHelm approved these changes

2022-05-13 15:58 UTC, MaureenHelm commented
Is there a PR to the main zephyr repo updating the manifest?

2022-05-13 16:03 UTC, yperess reviewed
Should we send this to upstream first?

2022-05-13 16:05 UTC, yperess requested changes
I would feel better if we sent this to upstream AOSP instead.

2022-05-13 16:05 UTC, MaureenHelm commented
> Should we send this to upstream first?

good point, yes

2022-05-13 16:47 UTC, yperess commented
@gmarull would you like me to make the upstream patch or would you?

2022-05-13 17:14 UTC, gmarull commented
> @gmarull would you like me to make the upstream patch or would you?

@yperess Where should I submit the patch?

2022-05-13 17:21 UTC, yperess commented
> > @gmarull would you like me to make the upstream patch or would you?
> 
> @yperess Where should I submit the patch?

https://source.android.com/setup/contribute/submit-patches has instructions for uploading to Gerrit

2022-06-16 18:18 UTC, yperess commented
@gmarull any update on this?

2022-06-20 09:25 UTC, gmarull commented
> @gmarull any update on this?

I haven't had time yet, feel free to proceed.

2022-08-24 18:08 UTC, closed without merging