zephyr: Make CONFIG_CHRE select CONFIG_REQUIRES_FULL_LIBCPP
zephyrproject-rtos/chre pull request #7
Opened 2022-12-09 18:01 UTC by stephanosio

This commit makes the Kconfig `CONFIG_CHRE` symbol select the `CONFIG_REQUIRES_FULL_LIBCPP` symbol because the CHRE library requires a fully featured C++ standard library.

Signed-off-by: Stephanos Ioannidis <stephanos.ioannidis@nordicsemi.no>

2022-12-12 20:07 UTC, yperess requested changes
Can we make this change upstream first? It gets really hard to pull changes otherwise. Would you like me to do it?

2022-12-12 20:22 UTC, yperess commented
see https://android-review.git.corp.google.com/c/platform/system/chre/+/2345027

2022-12-13 05:24 UTC, stephanosio commented
Public URL: https://android-review.googlesource.com/c/platform/system/chre/+/2345027

2022-12-15 13:27 UTC, stephanosio commented
@yperess https://android-review.googlesource.com/c/platform/system/chre/+/2345027 was merged.

2022-12-15 20:56 UTC, yperess commented
Looking to see if we can fast forward. If this is blocking lets just merge this and I'll deal with cleaning things up later. Let me know. I'll try to have the fast forward today for you either way.

2023-01-09 14:45 UTC, stephanosio commented
> Looking to see if we can fast forward. If this is blocking lets just merge this and I'll deal with cleaning things up later. Let me know. I'll try to have the fast forward today for you either way.

@yperess Any updates?

2023-01-09 20:45 UTC, yperess commented
> > Looking to see if we can fast forward. If this is blocking lets just merge this and I'll deal with cleaning things up later. Let me know. I'll try to have the fast forward today for you either way.
> 
> @yperess Any updates?

Sorry, just got back from the holiday vacation last week on Thursday and I'm still catching up. I'm having issues pulling https://android.googlesource.com/platform/system/chre/+/7473dd7de7f0a4067d5f7f429ae65b30718da1d0 without a huge diff, but I think that's just how it's going to need to be since it's pulling Android 13's changes. I'll send you the full `git merge` in a few minutes. I usually use a `--ff-only` for these pulls but it seems that because of the way we merged the last PR with a merge commit (I think) it's causing an issue where we can't fast forward.

2023-01-10 23:39 UTC, yperess approved these changes

2023-01-11 11:06 UTC, merged